repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.6.1
    hooks:
    -   id: reorder-python-imports

-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3.7
